package:
  name: bbl
  version: 6.7.15  
  targets:
  - platform: linux   
    architecture: amd64
    - download:
        url: https://github.com/cloudfoundry/bosh-bootloader/releases/download/v((version))/bbl-v((version))_linux_x86-64      
        out: bbl-v6.7.15_linux_x86-64
  - platform: windows    
    architecture: amd64
    - download:    
        url: https://github.com/cloudfoundry/bosh-bootloader/releases/download/v((version))/bbl-v((version))_windows.exe
        out: bbl-v6.7.15_windows.exe
  - platform: darwin
    architecture: amd64
    - download:
        url: https://github.com/cloudfoundry/bosh-bootloader/releases/download/v((version))/bbl-v((version))_osx
        out: bbl-v6.7.15_osx