package: 
  name: bbr
  version: 1.9.1
  targets:
  - platform: linux
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.9.1/bbr-1.9.1-linux-amd64.tar
        out: bbr-1.9.1-linux.tar
    - extract:
        archive: bbr-1.9.1-linux.tar
    - move:
        source: bbr
        destination: bbr-1.9.1-linux    
  - platform: darwin
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.9.1/bbr-1.9.1-darwin-amd64.tar
        out: bbr-1.9.1-darwin.tar
    - extract:
        archive: bbr-1.9.1-darwin.tar
    - move:
        source: bbr-mac
        destination: bbr-1.9.1-darwin