package:
  name: fly
  version: 7.14.1
  targets:
  - platform: darwin
    architecture: amd64
    executables:
    - fly
    steps:
    - download:
        url: https://github.com/concourse/concourse/releases/download/v7.14.1/fly-7.14.1-darwin-amd64.tgz
        out: fly-7.14.1-darwin-amd64.tgz
    - extract:
        archive: fly-7.14.1-darwin-amd64.tgz
  - platform: linux
    architecture: amd64
    executables:
    - fly
    steps:
    - download:
        url: https://github.com/concourse/concourse/releases/download/v7.14.1/fly-7.14.1-linux-amd64.tgz
        out: fly-7.14.1-linux-amd64.tgz
    - extract:
        archive: fly-7.14.1-linux-amd64.tgz
  - platform: windows
    architecture: amd64
    executables:
    - fly.exe
    steps:
    - download:
        url: https://github.com/concourse/concourse/releases/download/v7.14.1/fly-7.14.1-windows-amd64.zip
        out: fly-7.14.1-windows-amd64.zip
    - extract:
        archive: fly-7.14.1-windows-amd64.zip
  
