package:
  name: fly
  version: 4.2.1
  targets:
  - platform: windows
    architecture: amd64
    executables:
    - fly.exe
    steps:
    - action: download
      with:
        url: https://github.com/concourse/concourse/releases/download/v4.2.1/fly_windows_amd64.exe
        out: fly_4.2.1_windows_amd64.exe
  - platform: darwin
    architecture: amd64
    executables:
    - fly
    steps:
    - action: download
      with:
        url: https://github.com/concourse/concourse/releases/download/v4.2.1/fly_darwin_amd64
        out: fly_4.2.1_darwin_amd64
  - platform: linux
    architecture: amd64
    executables:
    - fly
    steps:
    - action: download
      with:
        url: https://github.com/concourse/concourse/releases/download/v4.2.1/fly_linux_amd64
        out: fly_4.2.1_linux_amd64
