package:
  name: fly
  version: 6.7.6
  targets:
  - platform: darwin
    architecture: amd64
    executables:
    - fly
    steps:
    - action: download
      with:
        url: https://github.com/concourse/concourse/releases/download/v6.7.6/fly-6.7.6-darwin-amd64.tgz
        out: fly-6.7.6-darwin-amd64.tgz
    - action: extract
      with:
        archive: fly-6.7.6-darwin-amd64.tgz
  - platform: linux
    architecture: amd64
    executables:
    - fly
    steps:
    - action: download
      with:
        url: https://github.com/concourse/concourse/releases/download/v6.7.6/fly-6.7.6-linux-amd64.tgz
        out: fly-6.7.6-linux-amd64.tgz
    - action: extract
      with:
        archive: fly-6.7.6-linux-amd64.tgz
  - platform: windows
    architecture: amd64
    executables:
    - fly.exe
    steps:
    - action: download
      with:
        url: https://github.com/concourse/concourse/releases/download/v6.7.6/fly-6.7.6-windows-amd64.zip
        out: fly-6.7.6-windows-amd64.zip
    - action: extract
      with:
        archive: fly-6.7.6-windows-amd64.zip
