package:
name: pack
version: 0.18.0
targets:
- platform: linux
    architecture: amd64
    steps:
    - action: download
      with:
        url: https://github.com/buildpacks/pack/releases/download/v0.18.0/pack-v0.18.0-linux.tgz
        out: pack-0.18.0-linux-amd64.tgz
    - action: extract
      with:
        archive: pack-0.18.0-linux-amd64.tgz
- platform: darwin
    architecture: amd64
    steps:
    - action: download
      with:
        url: https://github.com/buildpacks/pack/releases/download/v0.18.0/pack-v0.18.0-macos.tgz
        out: pack-0.18.0-darwin-amd64.tgz
    - action: extract
      with:
        archive: pack-0.18.0-darwin-amd64.tgz
- platform: darwin
    architecture: arm64
    steps:
    - action: download
      with:
        url: https://github.com/buildpacks/pack/releases/download/v0.18.0/pack-v0.18.0-macos-arm64.tgz
        out: pack-0.18.0-darwin-arm64.tgz
    - action: extract
      with:
        archive: pack-0.18.0-darwin-arm64.tgz
- platform: windows
    architecture: amd64
    steps:
    - action: download
      with:
        url: https://github.com/buildpacks/pack/releases/download/v0.18.0/pack-v0.18.0-windows.zip
        out: pack-0.18.0-windows-amd64.zip
    - action: extract
      with:
        archive: pack-0.18.0-windows-amd64.zip
  
