pool:
  vmImage: 'ubuntu-latest'

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
    
steps:
- task: Bash@3
  inputs:
    filePath: 'scripts/update-packages.sh'