name: bbr
version: 1.3.2
targets:
- platform: linux 
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v((version))/bbr-((version))-linux-amd64
      out: bbr-((version))-linux
- platform: darwin
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v((version))/bbr-((version))-darwin-amd64
      out: bbr-((version))-darwin  