name: bbr
version: 1.3.2
targets:
- platform: linux 
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.3.2/bbr-1.3.2-linux-amd64
      out: bbr-1.3.2-linux
- platform: darwin
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.3.2/bbr-1.3.2-darwin-amd64
      out: bbr-1.3.2-darwin  