name: wrangle
version: 0.9.0
targets:
- platform: linux
  tasks:
  - download:
      url: https://github.com/patrickhuber/wrangle/releases/download/0.9.0/wrangle-linux-amd64.tgz
      out: wrangle-((version))-linux-amd64.tgz
  - extract:
      archive: wrangle-((version))-linux-amd64.tgz
- platform: darwin
  tasks:
  - download:
      url: https://github.com/patrickhuber/wrangle/releases/download/0.9.0/wrangle-darwin-amd64.tgz
      out: wrangle-((version))-darwin-amd64.tgz
  - extract:
      archive: wrangle-((version))-darwin-amd64.tgz
- platform: windows
  tasks:
  - download:
      url: https://github.com/patrickhuber/wrangle/releases/download/0.9.0/wrangle-windows-amd64.zip
      out: wrangle-((version))-windows.zip
  - extract:
      archive: wrangle-((version))-windows.zip
