package: 
  name: wrangle
  version: 0.9.0
  targets:
  - platform: linux
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/v0.9.0/wrangle-0.9.0-linux-amd64.tar.gz
        out: wrangle-0.9.0-linux-amd64.tar.gz
    - extract:
        archive: wrangle-0.9.0-linux-amd64.tar.gz
    - move:
        source: wrangle
        destination: wrangle-0.9.0-linux-amd64
  - platform: darwin
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/v0.9.0/wrangle-0.9.0-darwin-amd64.tar.gz
        out: wrangle-0.9.0-darwin-amd64.tar.gz
    - extract:
        archive: wrangle-0.9.0-darwin-amd64.tar.gz
    - move:
        source: wrangle
        destination: wrangle-0.9.0-darwin-amd64
  - platform: windows
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/v0.9.0/wrangle-0.9.0-windows-amd64.zip
        out: wrangle-0.9.0-windows-amd64.zip
    - extract:
        archive: wrangle-0.9.0-windows-amd64.zip
    - move:
        source: wrangle.exe
        destination: wrangle-0.9.0-windows-amd64.exe
  
