package: 
  name: wrangle
  version: 0.8.0
  targets:
  - platform: linux
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/0.8.0/wrangle-linux-amd64.tgz
        out: wrangle-0.8.0-linux-amd64.tgz
    - extract:
        archive: wrangle-0.8.0-linux-amd64.tgz
    - move:
        source: wrangle
        destination: wrangle-0.8.0-linux-amd64
  - platform: darwin
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/0.8.0/wrangle-darwin-amd64.tgz
        out: wrangle-0.8.0-darwin-amd64.tgz
    - extract:
        archive: wrangle-0.8.0-darwin-amd64.tgz
    - move:
        source: wrangle
        destination: wrangle-0.8.0-darwin-amd64
  - platform: windows
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/0.8.0/wrangle-windows-amd64.zip
        out: wrangle-0.8.0-windows-amd64.zip
    - extract:
        archive: wrangle-0.8.0-windows-amd64.zip
    - move:
        source: wrangle.exe
        destination: wrangle-0.8.0-windows-amd64.exe
  
