package:
  name: pack
  version: 0.17.0
  targets:
  - platform: linux
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/buildpacks/pack/releases/download/v0.17.0/pack-v0.17.0-linux.tgz
        out: pack-0.17.0-linux-amd64.tgz
    - extract:
        archive: pack-0.17.0-linux-amd64.tgz
    - move: 
        source: pack
        destination: pack-0.17.0-linux-amd64
  - platform: darwin
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/buildpacks/pack/releases/download/v0.17.0/pack-v0.17.0-macos.tgz
        out: pack-0.17.0-darwin-amd64.tgz
    - extract:
        archive: pack-0.17.0-darwin-amd64.tgz
    - move: 
        source: pack
        destination: pack-0.17.0-darwin-amd64
  - platform: darwin
    architecture: arm64
    tasks:
    - download:
        url: https://github.com/buildpacks/pack/releases/download/v0.17.0/pack-v0.17.0-macos-arm64.tgz
        out: pack-0.17.0-darwin-arm64.tgz
    - extract:
        archive: pack-0.17.0-darwin-arm64.tgz
    - move: 
        source: pack
        destination: pack-0.17.0-darwin-arm64
  - platform: windows
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/buildpacks/pack/releases/download/v0.17.0/pack-v0.17.0-windows.zip
        out: pack-0.17.0-windows-amd64.zip
    - extract:
        archive: pack-0.17.0-windows-amd64.zip
    - move: 
        source: pack.exe
        destination: pack-0.17.0-windows-amd64.exe
  
