package: 
  name: yq
  version: 4.5.1
  targets:
  - platform: darwin
    architecture: amd64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_darwin_amd64.tar.gz
        out: yq-4.5.1-darwinamd64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-darwinamd64.tar.gz
    - action: move
      with:
        source: yq_darwin_amd64
        destination: yq
  - platform: freebsd
    architecture: 386
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_freebsd_386.tar.gz
        out: yq-4.5.1-freebsd386.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-freebsd386.tar.gz
    - action: move
      with:
        source: yq_freebsd_386
        destination: yq
  - platform: freebsd
    architecture: amd64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_freebsd_amd64.tar.gz
        out: yq-4.5.1-freebsdamd64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-freebsdamd64.tar.gz
    - action: move
      with:
        source: yq_freebsd_amd64
        destination: yq
  - platform: linux
    architecture: amd64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_linux_amd64.tar.gz
        out: yq-4.5.1-linuxamd64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-linuxamd64.tar.gz
    - action: move
      with:
        source: yq_linux_amd64
        destination: yq
  - platform: linux
    architecture: arm
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_linux_arm.tar.gz
        out: yq-4.5.1-linuxarm.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-linuxarm.tar.gz
    - action: move
      with:
        source: yq_linux_arm
        destination: yq
  - platform: linux
    architecture: arm64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_linux_arm64.tar.gz
        out: yq-4.5.1-linuxarm64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-linuxarm64.tar.gz
    - action: move
      with:
        source: yq_linux_arm64
        destination: yq
  - platform: linux
    architecture: mips64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_linux_mips64.tar.gz
        out: yq-4.5.1-linuxmips64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-linuxmips64.tar.gz
    - action: move
      with:
        source: yq_linux_mips64
        destination: yq
  - platform: linux
    architecture: mips64le
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_linux_mips64le.tar.gz
        out: yq-4.5.1-linuxmips64le.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-linuxmips64le.tar.gz
    - action: move
      with:
        source: yq_linux_mips64le
        destination: yq
  - platform: linux
    architecture: ppc64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_linux_ppc64.tar.gz
        out: yq-4.5.1-linuxppc64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-linuxppc64.tar.gz
    - action: move
      with:
        source: yq_linux_ppc64
        destination: yq
  - platform: linux
    architecture: s390x
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_linux_s390x.tar.gz
        out: yq-4.5.1-linuxs390x.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-linuxs390x.tar.gz
    - action: move
      with:
        source: yq_linux_s390x
        destination: yq
  - platform: netbsd
    architecture: 386
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_netbsd_386.tar.gz
        out: yq-4.5.1-netbsd386.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-netbsd386.tar.gz
    - action: move
      with:
        source: yq_netbsd_386
        destination: yq
  - platform: netbsd
    architecture: arm
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_netbsd_arm.tar.gz
        out: yq-4.5.1-netbsdarm.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-netbsdarm.tar.gz
    - action: move
      with:
        source: yq_netbsd_arm
        destination: yq
  - platform: netbsd
    architecture: amd64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_netbsd_amd64.tar.gz
        out: yq-4.5.1-netbsdamd64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-netbsdamd64.tar.gz
    - action: move
      with:
        source: yq_netbsd_amd64
        destination: yq
  - platform: openbsd
    architecture: 386
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_openbsd_386.tar.gz
        out: yq-4.5.1-openbsd386.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-openbsd386.tar.gz
    - action: move
      with:
        source: yq_openbsd_386
        destination: yq
  - platform: openbsd
    architecture: amd64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_openbsd_amd64.tar.gz
        out: yq-4.5.1-openbsdamd64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-openbsdamd64.tar.gz
    - action: move
      with:
        source: yq_openbsd_amd64
        destination: yq
  - platform: windows
    architecture: 386
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_windows_386.tar.gz
        out: yq-4.5.1-windows386.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-windows386.tar.gz
    - action: move
      with:
        source: yq_windows_386.exe
        destination: yq.exe
  - platform: windows
    architecture: amd64
    tasks:
    - action: download
      with:
        url: https://github.com/mikefarah/yq/releases/download/v4.5.1/yq_windows_amd64.tar.gz
        out: yq-4.5.1-windowsamd64.tar.gz
    - action: extract
      with:
        archive: yq-4.5.1-windowsamd64.tar.gz
    - action: move
      with:
        source: yq_windows_amd64.exe
        destination: yq.exe
  
