package: 
  name: shim
  version: 0.0.1
  targets:
  - platform: linux
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/shim/releases/download/v0.0.1/shim-0.0.1-linux-amd64.tar.gz
        out: shim-0.0.1-linux-amd64.tar.gz
    - extract:
        archive: shim-0.0.1-linux-amd64.tar.gz
  - platform: darwin
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/shim/releases/download/v0.0.1/shim-0.0.1-darwin-amd64.tar.gz
        out: shim-0.0.1-darwin-amd64.tar.gz
    - extract:
        archive: shim-0.0.1-darwin-amd64.tar.gz
  - platform: windows
    architecture: amd64
    tasks:
    - download:    
        url: https://github.com/patrickhuber/shim/releases/download/v0.0.1/shim-0.0.1-windows-amd64.zip
        out: shim-0.0.1-windows-amd64.zip
    - extract:
        archive: shim-0.0.1-windows-amd64.zip
