package: 
  name: bbr
  version: 1.9.5
  targets:
  - platform: linux
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.9.5/bbr-1.9.5-linux-amd64.tar
        out: bbr-1.9.5-linux.tar
    - extract:
        archive: bbr-1.9.5-linux.tar
  - platform: darwin
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.9.5/bbr-1.9.5-darwin-amd64.tar
        out: bbr-1.9.5-darwin.tar
    - extract:
        archive: bbr-1.9.5-darwin.tar
  
