package:
  name: fly
  version: 7.0.0
  targets:
  - platform: darwin
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/concourse/concourse/releases/download/v7.0.0/fly-7.0.0-darwin-amd64.tgz
        out: fly-7.0.0-darwin-amd64.tgz
    - extract:
        archive: fly-7.0.0-darwin-amd64.tgz
    - move:
        source: fly
        destination: fly-7.0.0-darwin-amd64
  - platform: linux
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/concourse/concourse/releases/download/v7.0.0/fly-7.0.0-linux-amd64.tgz
        out: fly-7.0.0-linux-amd64.tgz
    - extract:
        archive: fly-7.0.0-linux-amd64.tgz
    - move:
        source: fly
        destination: fly-7.0.0-linux-amd64
  - platform: windows
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/concourse/concourse/releases/download/v7.0.0/fly-7.0.0-windows-amd64.zip
        out: fly-7.0.0-windows-amd64.zip
    - extract:
        archive: fly-7.0.0-windows-amd64.zip
    - move:
        source: fly.exe
        destination: fly-7.0.0-windows-amd64.exe
  
