package: 
  name: wrangle
  version: 0.10.3
  targets:
  - platform: linux
    architecture: amd64
    executables:
    - wrangle
    steps:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/v0.10.3/wrangle-0.10.3-linux-amd64.tar.gz
        out: wrangle-0.10.3-linux-amd64.tar.gz
    - extract:
        archive: wrangle-0.10.3-linux-amd64.tar.gz
  - platform: darwin
    architecture: amd64
    executables:
    - wrangle
    steps:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/v0.10.3/wrangle-0.10.3-darwin-amd64.tar.gz
        out: wrangle-0.10.3-darwin-amd64.tar.gz
    - extract:
        archive: wrangle-0.10.3-darwin-amd64.tar.gz
  - platform: darwin
    architecture: arm64
    executables:
    - wrangle
    steps:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/v0.10.3/wrangle-0.10.3-darwin-arm64.tar.gz
        out: wrangle-0.10.3-darwin-arm64.tar.gz
    - extract:
        archive: wrangle-0.10.3-darwin-arm64.tar.gz
  - platform: windows
    architecture: amd64
    executables:
    - wrangle.exe
    steps:
    - download:    
        url: https://github.com/patrickhuber/wrangle/releases/download/v0.10.3/wrangle-0.10.3-windows-amd64.zip
        out: wrangle-0.10.3-windows-amd64.zip
    - extract:
        archive: wrangle-0.10.3-windows-amd64.zip
  

