name: cf
version: 6.37.0
targets:
- platform: linux
  architecture: amd64
  tasks:
  - download:
      url: https://packages.cloudfoundry.org/stable?release=linux64-binary&version=((version))&source=github-rel
      out: cf_cli_((version))_linux_amd64.tgz
  - extract:
      archive: cf_cli_((version))_linux_amd64.tgz
- platform: darwin
  architecture: amd64
  tasks:
  - download:
      url: https://packages.cloudfoundry.org/stable?release=macosx64-binary&version=((version))&source=github-rel
      out: cf_cli_((version))_darwin_amd64.tgz
  - extract:
      archive: cf_cli_((version))_darwin_amd64.tgz
- platform: windows
  architecture: amd64
  tasks:
  - download:
      url: https://packages.cloudfoundry.org/stable?release=windows64-exe&version=((version))&source=github-rel
      out: cf-cli_((version))_windows_amd64.zip
  - extract:
      archive: cf-cli_((version))_windows_amd64.zip
