name: jq
version: 1.6
targets:
- platform: windows
  tasks: 
  - download: 
      url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
      out: jq_((version))_win64.exe
- platform: darwin
  tasks:
  - download:
      url: https://github.com/stedolan/jq/releases/download/jq-((version))/jq-osx-amd64
      out: jq_((version))_osx_amd64
- platform: linux
  tasks:
  - download:
      url: https://github.com/stedolan/jq/releases/download/jq-((version))/jq-linux64
      out: jq_((version))_linux_64