package: 
  name: yq
  version: 4.6.3
  targets:
  - platform: darwin
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_darwin_amd64.tar.gz
        out: yq-4.6.3-darwinamd64.tar.gz
    - extract:
        archive: yq-4.6.3-darwinamd64.tar.gz
    - move:
        source: yq_darwin_amd64
        destination: yq-4.6.3-darwin-amd64
  - platform: freebsd
    architecture: 386
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_freebsd_386.tar.gz
        out: yq-4.6.3-freebsd386.tar.gz
    - extract:
        archive: yq-4.6.3-freebsd386.tar.gz
    - move:
        source: yq_freebsd_386
        destination: yq-4.6.3-freebsd-386
  - platform: freebsd
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_freebsd_amd64.tar.gz
        out: yq-4.6.3-freebsdamd64.tar.gz
    - extract:
        archive: yq-4.6.3-freebsdamd64.tar.gz
    - move:
        source: yq_freebsd_amd64
        destination: yq-4.6.3-freebsd-amd64
  - platform: linux
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_amd64.tar.gz
        out: yq-4.6.3-linuxamd64.tar.gz
    - extract:
        archive: yq-4.6.3-linuxamd64.tar.gz
    - move:
        source: yq_linux_amd64
        destination: yq-4.6.3-linux-amd64
  - platform: linux
    architecture: arm
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_arm.tar.gz
        out: yq-4.6.3-linuxarm.tar.gz
    - extract:
        archive: yq-4.6.3-linuxarm.tar.gz
    - move:
        source: yq_linux_arm
        destination: yq-4.6.3-linux-arm
  - platform: linux
    architecture: arm64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_arm64.tar.gz
        out: yq-4.6.3-linuxarm64.tar.gz
    - extract:
        archive: yq-4.6.3-linuxarm64.tar.gz
    - move:
        source: yq_linux_arm64
        destination: yq-4.6.3-linux-arm64
  - platform: linux
    architecture: mips64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_mips64.tar.gz
        out: yq-4.6.3-linuxmips64.tar.gz
    - extract:
        archive: yq-4.6.3-linuxmips64.tar.gz
    - move:
        source: yq_linux_mips64
        destination: yq-4.6.3-linux-mips64
  - platform: linux
    architecture: mips64le
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_mips64le.tar.gz
        out: yq-4.6.3-linuxmips64le.tar.gz
    - extract:
        archive: yq-4.6.3-linuxmips64le.tar.gz
    - move:
        source: yq_linux_mips64le
        destination: yq-4.6.3-linux-mips64le
  - platform: linux
    architecture: ppc64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_ppc64.tar.gz
        out: yq-4.6.3-linuxppc64.tar.gz
    - extract:
        archive: yq-4.6.3-linuxppc64.tar.gz
    - move:
        source: yq_linux_ppc64
        destination: yq-4.6.3-linux-ppc64
  - platform: linux
    architecture: s390x
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_s390x.tar.gz
        out: yq-4.6.3-linuxs390x.tar.gz
    - extract:
        archive: yq-4.6.3-linuxs390x.tar.gz
    - move:
        source: yq_linux_s390x
        destination: yq-4.6.3-linux-s390x
  - platform: netbsd
    architecture: 386
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_netbsd_386.tar.gz
        out: yq-4.6.3-netbsd386.tar.gz
    - extract:
        archive: yq-4.6.3-netbsd386.tar.gz
    - move:
        source: yq_netbsd_386
        destination: yq-4.6.3-netbsd-386
  - platform: netbsd
    architecture: arm
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_netbsd_arm.tar.gz
        out: yq-4.6.3-netbsdarm.tar.gz
    - extract:
        archive: yq-4.6.3-netbsdarm.tar.gz
    - move:
        source: yq_netbsd_arm
        destination: yq-4.6.3-netbsd-arm
  - platform: netbsd
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_netbsd_amd64.tar.gz
        out: yq-4.6.3-netbsdamd64.tar.gz
    - extract:
        archive: yq-4.6.3-netbsdamd64.tar.gz
    - move:
        source: yq_netbsd_amd64
        destination: yq-4.6.3-netbsd-amd64
  - platform: openbsd
    architecture: 386
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_openbsd_386.tar.gz
        out: yq-4.6.3-openbsd386.tar.gz
    - extract:
        archive: yq-4.6.3-openbsd386.tar.gz
    - move:
        source: yq_openbsd_386
        destination: yq-4.6.3-openbsd-386
  - platform: openbsd
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_openbsd_amd64.tar.gz
        out: yq-4.6.3-openbsdamd64.tar.gz
    - extract:
        archive: yq-4.6.3-openbsdamd64.tar.gz
    - move:
        source: yq_openbsd_amd64
        destination: yq-4.6.3-openbsd-amd64
  - platform: windows
    architecture: 386
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_windows_386.tar.gz
        out: yq-4.6.3-windows386.tar.gz
    - extract:
        archive: yq-4.6.3-windows386.tar.gz
    - move:
        source: yq_windows_386.exe
        destination: yq-4.6.3-windows-386.exe
  - platform: windows
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_windows_amd64.tar.gz
        out: yq-4.6.3-windowsamd64.tar.gz
    - extract:
        archive: yq-4.6.3-windowsamd64.tar.gz
    - move:
        source: yq_windows_amd64.exe
        destination: yq-4.6.3-windows-amd64.exe
  
