# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # triggers the workflow on a specified schedule  
  schedule:
    # this schedule will run every hour https://crontab.guru/every-1-hour
  - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install required packages
      - name: Install Packages
        env:
          YQ_BINARY: yq_linux_amd64
          YQ_VERSION: v4.5.1
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}.tar.gz -O - | tar xz && sudo mv ${YQ_BINARY} /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Latest Packages
        run: |
          ls feed -1a | while read package
          do
            echo "$package"
          done