# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install required dependencies
      - name: Install Dependencies
        env:
          YQ_BINARY: yq_linux_amd64
          YQ_VERSION: v4.5.1
          RENDERIZER_VERSION: v2.0.11          
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}.tar.gz -O - | tar xz && sudo mv ${YQ_BINARY} /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          sudo wget https://github.com/gomatic/renderizer/releases/download/${RENDERIZER_VERSION}/renderizer_linux_amd64 -O /usr/bin/renderizer
          sudo chmod +x /usr/bin/renderizer

      # Run through each package and process the template for the latest version in the resource
      - name: Update Latest Packages
        run: ./scripts/update-packages.sh

      # create a branch for the changes based on the workflow run number
      - name: Create Branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b update-packages-${{ github.run_id }}
          git add .
          git commit -m "Update packages to latest versions"
          git push --set-upstream origin update-packages-${{ github.run_id }}
    
      # Create a pull request for the changes
      - name: Create Pull Request
        run: gh pr create --title "Update packages to latest versions" --body "This PR updates the packages to their latest versions." --head update-packages-${{ github.run_id }} --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          