package:
  name: renderizer
  version: 2.0.11
  targets:
  - platform: linux
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/gomatic/renderizer/releases/download/v2.0.11/renderizer_linux_x86_64.tar.gz
        out: renderizer-2.0.11-linux-amd64.tar.gz
    - extract:
        archive: renderizer-2.0.11-linux-amd64.tar.gz
  - platform: windows
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/gomatic/renderizer/releases/download/v2.0.11/renderizer_windows_x86_64.zip
        out: renderizer-2.0.11-windows-amd64.zip
    - extract:
        archive: renderizer-2.0.11-windows-amd64.zip
  - platform: darwin
    architecture: amd64
    tasks:
    - download:
        url: https://github.com/gomatic/renderizer/releases/download/v2.0.11/renderizer_darwin_x86_64.tar.gz
        out: renderizer-2.0.11-darwin-amd64.tar.gz
    - extract:
        archive: renderizer-2.0.11-darwin-amd64.tar.gz
  
